language: ruby
sudo: required

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_4a3430b8d014_key -iv $encrypted_4a3430b8d014_iv
  -in secret.txt.enc -out scripts/secret.txt -d

script:
- docker build -t cgal/bundle-3d-demo .

after_success:
- source scripts/secret.txt
- if [ "$TRAVIS_EVENT_TYPE" != "pull_request" -a "$TRAVIS_BRANCH" = "master" ]; then docker login -u lrineau -p $PASS; docker push cgal/bundle-3d-demo; fi
